2021-02-12 21:35:47,463 ERROR: Exception on /post/01 [GET] [in c:\users\yacho\pycharmprojects\flaskproject\venv\lib\site-packages\flask\app.py:1891]
Traceback (most recent call last):
  File "c:\users\yacho\pycharmprojects\flaskproject\venv\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\yacho\pycharmprojects\flaskproject\venv\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\yacho\pycharmprojects\flaskproject\venv\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\yacho\pycharmprojects\flaskproject\venv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "c:\users\yacho\pycharmprojects\flaskproject\venv\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\yacho\pycharmprojects\flaskproject\venv\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\yacho\PycharmProjects\flaskProject\app\routes.py", line 155, in post
    posts = Post.query.filter_by(id).first()
TypeError: filter_by() takes 1 positional argument but 2 were given
2021-02-12 21:36:39,975 INFO: Microblog startup [in C:\Users\yacho\PycharmProjects\flaskProject\app\__init__.py:46]
2021-02-12 21:36:43,981 ERROR: Exception on /post/01 [GET] [in c:\users\yacho\pycharmprojects\flaskproject\venv\lib\site-packages\flask\app.py:1891]
Traceback (most recent call last):
  File "c:\users\yacho\pycharmprojects\flaskproject\venv\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\yacho\pycharmprojects\flaskproject\venv\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\yacho\pycharmprojects\flaskproject\venv\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\yacho\pycharmprojects\flaskproject\venv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "c:\users\yacho\pycharmprojects\flaskproject\venv\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\yacho\pycharmprojects\flaskproject\venv\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\yacho\PycharmProjects\flaskProject\app\routes.py", line 156, in post
    return render_template("post.html", posts=posts, title=posts.title)
  File "c:\users\yacho\pycharmprojects\flaskproject\venv\lib\site-packages\flask\templating.py", line 137, in render_template
    return _render(
  File "c:\users\yacho\pycharmprojects\flaskproject\venv\lib\site-packages\flask\templating.py", line 120, in _render
    rv = template.render(context)
  File "c:\users\yacho\pycharmprojects\flaskproject\venv\lib\site-packages\jinja2\environment.py", line 1090, in render
    self.environment.handle_exception()
  File "c:\users\yacho\pycharmprojects\flaskproject\venv\lib\site-packages\jinja2\environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "c:\users\yacho\pycharmprojects\flaskproject\venv\lib\site-packages\jinja2\_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "C:\Users\yacho\PycharmProjects\flaskProject\app\templates\post.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "C:\Users\yacho\PycharmProjects\flaskProject\app\templates\base.html", line 31, in top-level template code
    {% block content %}{% endblock %}
  File "C:\Users\yacho\PycharmProjects\flaskProject\app\templates\post.html", line 5, in block "content"
    <td><img src="{{ post.author.avatar(36) }}"></td>
  File "c:\users\yacho\pycharmprojects\flaskproject\venv\lib\site-packages\jinja2\environment.py", line 471, in getattr
    return getattr(obj, attribute)
jinja2.exceptions.UndefinedError: 'post' is undefined
2021-02-12 21:37:17,945 INFO: Microblog startup [in C:\Users\yacho\PycharmProjects\flaskProject\app\__init__.py:46]
2021-02-12 21:37:25,181 ERROR: Exception on /post/01 [GET] [in c:\users\yacho\pycharmprojects\flaskproject\venv\lib\site-packages\flask\app.py:1891]
Traceback (most recent call last):
  File "c:\users\yacho\pycharmprojects\flaskproject\venv\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\yacho\pycharmprojects\flaskproject\venv\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\yacho\pycharmprojects\flaskproject\venv\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\yacho\pycharmprojects\flaskproject\venv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "c:\users\yacho\pycharmprojects\flaskproject\venv\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\yacho\pycharmprojects\flaskproject\venv\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\yacho\PycharmProjects\flaskProject\app\routes.py", line 156, in post
    return render_template("post.html", posts=posts, title=posts.title)
  File "c:\users\yacho\pycharmprojects\flaskproject\venv\lib\site-packages\flask\templating.py", line 137, in render_template
    return _render(
  File "c:\users\yacho\pycharmprojects\flaskproject\venv\lib\site-packages\flask\templating.py", line 120, in _render
    rv = template.render(context)
  File "c:\users\yacho\pycharmprojects\flaskproject\venv\lib\site-packages\jinja2\environment.py", line 1090, in render
    self.environment.handle_exception()
  File "c:\users\yacho\pycharmprojects\flaskproject\venv\lib\site-packages\jinja2\environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "c:\users\yacho\pycharmprojects\flaskproject\venv\lib\site-packages\jinja2\_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "C:\Users\yacho\PycharmProjects\flaskProject\app\templates\post.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "C:\Users\yacho\PycharmProjects\flaskProject\app\templates\base.html", line 31, in top-level template code
    {% block content %}{% endblock %}
  File "C:\Users\yacho\PycharmProjects\flaskProject\app\templates\post.html", line 5, in block "content"
    <td><img src="{{ post.author.avatar(36) }}"></td>
  File "c:\users\yacho\pycharmprojects\flaskproject\venv\lib\site-packages\jinja2\environment.py", line 471, in getattr
    return getattr(obj, attribute)
jinja2.exceptions.UndefinedError: 'post' is undefined
2021-02-12 21:37:27,019 ERROR: Exception on /post/01 [GET] [in c:\users\yacho\pycharmprojects\flaskproject\venv\lib\site-packages\flask\app.py:1891]
Traceback (most recent call last):
  File "c:\users\yacho\pycharmprojects\flaskproject\venv\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\yacho\pycharmprojects\flaskproject\venv\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\yacho\pycharmprojects\flaskproject\venv\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\yacho\pycharmprojects\flaskproject\venv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "c:\users\yacho\pycharmprojects\flaskproject\venv\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\yacho\pycharmprojects\flaskproject\venv\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\yacho\PycharmProjects\flaskProject\app\routes.py", line 156, in post
    return render_template("post.html", posts=posts, title=posts.title)
  File "c:\users\yacho\pycharmprojects\flaskproject\venv\lib\site-packages\flask\templating.py", line 137, in render_template
    return _render(
  File "c:\users\yacho\pycharmprojects\flaskproject\venv\lib\site-packages\flask\templating.py", line 120, in _render
    rv = template.render(context)
  File "c:\users\yacho\pycharmprojects\flaskproject\venv\lib\site-packages\jinja2\environment.py", line 1090, in render
    self.environment.handle_exception()
  File "c:\users\yacho\pycharmprojects\flaskproject\venv\lib\site-packages\jinja2\environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "c:\users\yacho\pycharmprojects\flaskproject\venv\lib\site-packages\jinja2\_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "C:\Users\yacho\PycharmProjects\flaskProject\app\templates\post.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "C:\Users\yacho\PycharmProjects\flaskProject\app\templates\base.html", line 31, in top-level template code
    {% block content %}{% endblock %}
  File "C:\Users\yacho\PycharmProjects\flaskProject\app\templates\post.html", line 5, in block "content"
    <td><img src="{{ post.author.avatar(36) }}"></td>
  File "c:\users\yacho\pycharmprojects\flaskproject\venv\lib\site-packages\jinja2\environment.py", line 471, in getattr
    return getattr(obj, attribute)
jinja2.exceptions.UndefinedError: 'post' is undefined
2021-02-12 21:38:00,878 INFO: Microblog startup [in C:\Users\yacho\PycharmProjects\flaskProject\app\__init__.py:46]
2021-02-12 21:48:29,915 INFO: Microblog startup [in C:\Users\yacho\PycharmProjects\flaskProject\app\__init__.py:46]
