2020-09-13 11:37:13,770 ERROR: Exception on /user/adada [GET] [in c:\users\yacho\pycharmprojects\flaskproject\venv\lib\site-packages\flask\app.py:1891]
Traceback (most recent call last):
  File "c:\users\yacho\pycharmprojects\flaskproject\venv\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\yacho\pycharmprojects\flaskproject\venv\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\yacho\pycharmprojects\flaskproject\venv\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\yacho\pycharmprojects\flaskproject\venv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "c:\users\yacho\pycharmprojects\flaskproject\venv\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\yacho\pycharmprojects\flaskproject\venv\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\users\yacho\pycharmprojects\flaskproject\venv\lib\site-packages\flask_login\utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "C:\Users\yacho\PycharmProjects\flaskProject\app\routes.py", line 88, in user
    posts = user.posts.order_by(Post.timestamp.desc()).paginate(page, app.config["POSTS_PER_PAGE"], False)
AttributeError: 'BaseQuery' object has no attribute 'posts'
2020-09-13 11:37:43,953 INFO: Microblog startup [in C:\Users\yacho\PycharmProjects\flaskProject\app\__init__.py:46]
2020-09-13 11:42:01,389 ERROR: Exception on /user/kkkk [GET] [in c:\users\yacho\pycharmprojects\flaskproject\venv\lib\site-packages\flask\app.py:1891]
Traceback (most recent call last):
  File "c:\users\yacho\pycharmprojects\flaskproject\venv\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\yacho\pycharmprojects\flaskproject\venv\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\yacho\pycharmprojects\flaskproject\venv\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\yacho\pycharmprojects\flaskproject\venv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "c:\users\yacho\pycharmprojects\flaskproject\venv\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\yacho\pycharmprojects\flaskproject\venv\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\users\yacho\pycharmprojects\flaskproject\venv\lib\site-packages\flask_login\utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "C:\Users\yacho\PycharmProjects\flaskProject\app\routes.py", line 91, in user
    return render_template('user.html', user=user, posts=posts.items, next_url=next_url, prev_url=prev_url)
  File "c:\users\yacho\pycharmprojects\flaskproject\venv\lib\site-packages\flask\templating.py", line 137, in render_template
    return _render(
  File "c:\users\yacho\pycharmprojects\flaskproject\venv\lib\site-packages\flask\templating.py", line 120, in _render
    rv = template.render(context)
  File "c:\users\yacho\pycharmprojects\flaskproject\venv\lib\site-packages\jinja2\environment.py", line 1090, in render
    self.environment.handle_exception()
  File "c:\users\yacho\pycharmprojects\flaskproject\venv\lib\site-packages\jinja2\environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "c:\users\yacho\pycharmprojects\flaskproject\venv\lib\site-packages\jinja2\_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "C:\Users\yacho\PycharmProjects\flaskProject\app\templates\user.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "C:\Users\yacho\PycharmProjects\flaskProject\app\templates\base.html", line 31, in top-level template code
    {% block content %}{% endblock %}
  File "C:\Users\yacho\PycharmProjects\flaskProject\app\templates\user.html", line 17, in block "content"
    {{ form.hidden_tag() }}
  File "c:\users\yacho\pycharmprojects\flaskproject\venv\lib\site-packages\jinja2\environment.py", line 471, in getattr
    return getattr(obj, attribute)
jinja2.exceptions.UndefinedError: 'form' is undefined
2020-09-13 11:44:08,324 INFO: Microblog startup [in C:\Users\yacho\PycharmProjects\flaskProject\app\__init__.py:46]
2020-09-13 11:44:58,413 ERROR: Exception on /user/adada [GET] [in c:\users\yacho\pycharmprojects\flaskproject\venv\lib\site-packages\flask\app.py:1891]
Traceback (most recent call last):
  File "c:\users\yacho\pycharmprojects\flaskproject\venv\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\yacho\pycharmprojects\flaskproject\venv\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\yacho\pycharmprojects\flaskproject\venv\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\yacho\pycharmprojects\flaskproject\venv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "c:\users\yacho\pycharmprojects\flaskproject\venv\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\yacho\pycharmprojects\flaskproject\venv\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\users\yacho\pycharmprojects\flaskproject\venv\lib\site-packages\flask_login\utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "C:\Users\yacho\PycharmProjects\flaskProject\app\routes.py", line 91, in user
    return render_template('user.html', user=user, posts=posts.items, next_url=next_url, prev_url=prev_url)
  File "c:\users\yacho\pycharmprojects\flaskproject\venv\lib\site-packages\flask\templating.py", line 137, in render_template
    return _render(
  File "c:\users\yacho\pycharmprojects\flaskproject\venv\lib\site-packages\flask\templating.py", line 120, in _render
    rv = template.render(context)
  File "c:\users\yacho\pycharmprojects\flaskproject\venv\lib\site-packages\jinja2\environment.py", line 1090, in render
    self.environment.handle_exception()
  File "c:\users\yacho\pycharmprojects\flaskproject\venv\lib\site-packages\jinja2\environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "c:\users\yacho\pycharmprojects\flaskproject\venv\lib\site-packages\jinja2\_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "C:\Users\yacho\PycharmProjects\flaskProject\app\templates\user.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "C:\Users\yacho\PycharmProjects\flaskProject\app\templates\base.html", line 31, in top-level template code
    {% block content %}{% endblock %}
  File "C:\Users\yacho\PycharmProjects\flaskProject\app\templates\user.html", line 17, in block "content"
    {{ form.hidden_tag() }}
  File "c:\users\yacho\pycharmprojects\flaskproject\venv\lib\site-packages\jinja2\environment.py", line 471, in getattr
    return getattr(obj, attribute)
jinja2.exceptions.UndefinedError: 'form' is undefined
2020-09-13 11:46:30,075 INFO: Microblog startup [in C:\Users\yacho\PycharmProjects\flaskProject\app\__init__.py:46]
2020-09-13 11:51:07,238 INFO: Microblog startup [in C:\Users\yacho\PycharmProjects\flaskProject\app\__init__.py:46]
